# Generated by Django 4.2.13 on 2024-05-22 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_attendance_id_alter_notice_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.RemoveField(
            model_name='teacherextra',
            name='user',
        ),
        migrations.DeleteModel(
            name='StudentExtra',
        ),
        migrations.DeleteModel(
            name='TeacherExtra',
        ),
    ]
