# Generated by Django 4.2.13 on 2024-05-22 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.RemoveField(
            model_name='teacherextra',
            name='user',
        ),
        migrations.DeleteModel(
            name='StudentExtra',
        ),
        migrations.DeleteModel(
            name='TeacherExtra',
        ),
    ]
