# Generated by Django 4.2.13 on 2024-05-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_remove_chargepointextra_mobile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChargePointExtra',
        ),
    ]
