# Generated by Django 4.2.13 on 2024-05-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_remove_chargepointextra_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargepointextra',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
