# Generated by Django 4.2.13 on 2024-05-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_client_alter_chargepointextra_joindate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
