# Generated by Django 4.2.13 on 2024-05-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargepointextra',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='chargepointextra',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='chargepointextra',
            name='status',
        ),
        migrations.RemoveField(
            model_name='chargepointextra',
            name='user',
        ),
        migrations.AddField(
            model_name='chargepointextra',
            name='model',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='chargepointextra',
            name='serial',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='chargepointextra',
            name='station',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
