# Generated by Django 4.2.13 on 2024-05-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_alter_chargepointextra_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('identifiant_bancaire', models.CharField(default='', max_length=50)),
                ('station', models.CharField(default='', max_length=100)),
                ('type_of_vehicle', models.CharField(default='', max_length=50)),
                ('joindate', models.DateField(default='')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='chargepointextra',
            name='joindate',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='chargepointextra',
            name='model',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='chargepointextra',
            name='serial',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='chargepointextra',
            name='station',
            field=models.CharField(default='', max_length=100),
        ),
    ]
