# Generated by Django 4.2.13 on 2024-06-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingSession',
            fields=[
                ('bank_id', models.CharField(max_length=20)),
                ('chargepoint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(default='', max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('payment_method', models.CharField(default='', max_length=50)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('process', 'In Process')], default='', max_length=10)),
            ],
        ),
    ]
